package:
  format-version: "1.0.0"
  name: "spi_uhf_transceiver_apps"
  version: "v1.0.1"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "spi_uhf_transceiver"
      type: "package"
      version: "v1.0.1"
    - name: "csp"
      type: "package"
      version: "v3.14.0"
    - name: "core"
      type: "package"
      version: "v3.11.1"
